oracionEj(1,e,1,[el,hombre,come,una,manzana]).
oracionEj(1,e,2,[la,mujer,come,manzanas]).
oracionEj(1,e,3,[maria,come,una,manzana,roja]).
oracionEj(1,e,4,[juan,ama,a,maria]).
oracionEj(1,e,5,[el,gato,grande,come,un,raton,gris]).
oracionEj(1,e,6,[juan,estudia,en,la,universidad]).
oracionEj(1,e,7,[el,alumno,ama,la,universidad]).
oracionEj(1,e,8,[el,gato,come,ratones]).
oracionEj(1,e,9,[el,raton,que,cazo,el,gato,era,gris]).
oracionEj(1,e,10,[la,universidad,es,grande]).

oracionEj(1,i,1,[the,man,eats,an,apple]).
oracionEj(1,i,2,[the,woman,eats,apples]).
oracionEj(1,i,3,[mary,eats,a,red,apple]).
oracionEj(1,i,4,[john,loves,mary]).
oracionEj(1,i,5,[the,big,cat,eats,a,grey,mouse]).
oracionEj(1,i,6,[john,studies,at,university]).
oracionEj(1,i,7,[the,student,loves,university]).
oracionEj(1,i,8,[the,cat,eats,mice]).
oracionEj(1,i,9,[the,mouse,that,the,cat,hunted,was,grey]).
oracionEj(1,i,10,[the,university,is,big]).

oracionEj(2,e,1,[el,hombre,come,una,manzana]).
oracionEj(2,e,2,[ellos,comen,manzanas]).
oracionEj(2,e,3,[tu,comes,una,manzana,roja]).
oracionEj(2,e,4,[juan,ama,a,maria]).
oracionEj(2,e,5,[el,gato,grande,come,un,raton,gris]).
oracionEj(2,e,6,[juan,estudia,en,la,universidad]).
oracionEj(2,e,7,[el,alumno,ama,la,universidad]).
oracionEj(2,e,8,[el,perro,persiguio,un,gato,negro,en,el,jardin]).
oracionEj(2,e,9,[la,universidad,es,grande]).
oracionEj(2,e,10,[el,hombre,que,vimos,ayer,es,mi,vecino]).
oracionEj(2,e,11,[el,canario,amarillo,canta,muy,bien]).
oracionEj(2,e,12,[juan,toma,un,cafe,y,lee,el,periodico]).
oracionEj(2,e,13,[juan,es,delgado,y,maria,es,alta]).
oracionEj(2,e,14,[oscar,wilde,escribio,el,fantasma,de,canterville]).

oracionEj(2,i,1,[the,man,eats,an,apple]).
oracionEj(2,i,2,[they,eat,some,apples]).
oracionEj(2,i,3,[you,eat,a,red,apple]).
oracionEj(2,i,4,[john,loves,mary]).
oracionEj(2,i,5,[the,big,cat,eats,a,grey,mouse]).
oracionEj(2,i,6,[john,studies,at,university]).
oracionEj(2,i,7,[the,student,loves,university]).
oracionEj(2,i,8,[the,dog,chased,a,black,cat,in,the,garden]).
oracionEj(2,i,9,[the,university,is,big]).
oracionEj(2,i,10,[the,man,that,we,saw,yesterday,is,my,neighbour]).
oracionEj(2,i,11,[the,yellow,canary,sings,very,well]).
oracionEj(2,i,12,[john,has,a,coffee,and,reads,the,newspaper]).
oracionEj(2,i,13,[john,is,thin,and,mary,is,tall]).
oracionEj(2,i,14,[oscar,wilde,wrote,the,canterville,ghost]).