(define (problem p1)
    (:domain blocks)
    (:objects A B C - block)
    (:init (ontable A) (clear A)
           (ontable B) (clear B)
           (ontable C) (clear C)
           (handempty)
    )
    (:goal (and (ontable C) (not (clear C))
                (on B C) (not (clear B))
                (on A B) (clear A)
           )
    )
)